# Browser walkthrough against tests/mock-server.mjs (Playwright, Python).
#   npm run build && node tests/mock-server.mjs &   then   python3 tests/ui-flow.py
# Screenshots go to tests/screenshots/.
import json, os, struct, sys, urllib.request
from playwright.sync_api import sync_playwright

BASE = "http://localhost:4599"
OUT = os.path.join(os.path.dirname(__file__), "screenshots")
os.makedirs(OUT, exist_ok=True)

def jpg(name):
    return {"name": name, "mimeType": "image/jpeg", "buffer": b"\xff\xd8\xff\xe0" + b"\x00" * 2000}

def mov(name):
    return {"name": name, "mimeType": "video/quicktime", "buffer": struct.pack(">I", 20) + b"ftypqt  " + b"\x00" * 4000}

def stats():
    return json.loads(urllib.request.urlopen(BASE + "/__stats").read())

failures = []
def check(cond, msg):
    print(("PASS " if cond else "FAIL ") + msg)
    if not cond:
        failures.append(msg)

with sync_playwright() as p:
    browser = p.chromium.launch()

    for label, vp in [("iphone", {"width": 390, "height": 844}), ("android", {"width": 412, "height": 915})]:
        page = browser.new_page(viewport=vp, device_scale_factor=2, is_mobile=True, has_touch=True)
        page.goto(BASE + "/e/jordan-and-taylor")
        page.wait_for_selector("text=Add your photos & videos")
        page.screenshot(path=f"{OUT}/{label}-1-landing.png")
        page.close()

    page = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    page.goto(BASE + "/e/jordan-and-taylor")
    page.wait_for_selector("text=Add your photos & videos")

    files = [jpg(f"IMG_20{i:02d}.JPG") for i in range(22)] + [jpg("IMG_FAIL_9999.JPG"), mov("IMG_3001.MOV"), jpg("IMG_REGFAIL.JPG"),
             {"name": "notes.jpg", "mimeType": "image/jpeg", "buffer": b"%PDF-1.7" + b"\x00" * 100}]
    page.set_input_files("input[type=file]", files)
    page.wait_for_selector("text=25 memories selected")
    check(page.locator("text=1 file can't be added").count() == 1, "renamed non-image rejected at selection")
    page.fill("input[autocomplete=name]", "Tanya Brooks")
    page.screenshot(path=f"{OUT}/iphone-2-review.png", full_page=True)

    page.click("text=Upload 25 memories")
    page.wait_for_selector("text=/Uploading \\d+ of 25/")
    page.wait_for_timeout(900)
    page.screenshot(path=f"{OUT}/iphone-3-progress.png", full_page=True)

    page.wait_for_selector("text=couldn't be uploaded", timeout=60000)
    page.screenshot(path=f"{OUT}/iphone-4-partial.png", full_page=True)
    s = stats()
    check(page.locator("text=23 memories uploaded.").count() == 1, "partial summary shows 23 uploaded")
    check(all(v == 1 for k, v in s["cloudinary"].items() if "FAIL" not in k), "each successful file sent to Cloudinary once")
    check(s["cloudinary"].get("IMG_REGFAIL.JPG") == 1, "file whose album save failed was uploaded once")

    page.click("text=Try 2 failed files again")
    page.wait_for_selector("text=Memories added!", timeout=60000)
    page.screenshot(path=f"{OUT}/iphone-5-success.png", full_page=True)
    s = stats()
    check(page.locator("text=Thanks, Tanya!").count() == 1, "thanks with first name")
    check(page.locator("text=Your 25 photos and videos have been added").count() == 1, "success count 25")
    check(s["cloudinary"].get("IMG_REGFAIL.JPG") == 1, "retrying a failed album save did not re-upload the file")
    check(s["cloudinary"].get("IMG_FAIL_9999.JPG") == 4, "failed file re-uploaded only on retry")
    check(all(v == 1 for k, v in s["cloudinary"].items() if "FAIL" not in k), "successful files never re-uploaded after retry")
    check(len(s["registered"]) == 25, "exactly 25 album records")

    page.click("text=Upload more")
    page.wait_for_selector("text=Add your photos & videos")

    for slug, text in [("closed-wedding", "Uploads for this event are now closed."), ("expired-wedding", "This gallery has expired."),
                       ("draft-wedding", "isn’t open for photos yet"), ("no-such-wedding", "Event not found")]:
        page.goto(f"{BASE}/e/{slug}")
        page.wait_for_selector(f"text={text}")
        check(True, f"{slug} shows correct message")
    page.goto(f"{BASE}/event/closed-wedding")
    page.wait_for_selector("text=now closed")
    page.screenshot(path=f"{OUT}/iphone-6-closed.png")
    page.close()

    # Marketing site and signup
    h = browser.new_page(viewport={"width": 1280, "height": 900})
    h.goto(BASE + "/?ref=bloom-planning")
    h.wait_for_selector("text=Every guest’s photos. One private album.")
    h.wait_for_timeout(400)
    h.screenshot(path=f"{OUT}/site-1-home.png", full_page=True)
    check(h.locator(".price-card").count() == 3, "home shows three plans")
    h.click("text=Choose Wedding Drop")
    h.wait_for_selector("text=Create your event")
    h.fill("input[placeholder=Jordan]", "Jordan")
    h.fill("input[placeholder=Taylor]", "Taylor")
    h.fill("input[type=date]", "2027-06-12")
    h.click("button.starter:has-text('Navy and Gold')")
    h.click("label.icon-option:has-text('Rings')")
    h.fill("input[type=email]", "jordan@example.com")
    h.fill("input[type=password]", "our secret pw")
    check(h.locator("text=guestphotodrop.com/e/jordan-and-taylor").count() == 1, "guest link preview from names")
    h.screenshot(path=f"{OUT}/site-2-start.png", full_page=True)
    h.click("text=Continue to payment · $79")
    h.wait_for_selector("text=Please agree to the Terms of Service")
    check(True, "checkout needs the terms box")
    h.check(".agree input")
    h.click("text=Continue to payment · $79")
    h.wait_for_selector("text=You’re all set!")
    su = stats()["lastSignup"]
    check(su["agreeTerms"] is True and su["ref"] == "bloom-planning", "partner ref and terms sent with checkout")
    check(h.locator("text=Open your dashboard").count() == 1, "welcome page after payment")
    h.wait_for_timeout(500)
    h.screenshot(path=f"{OUT}/site-3-welcome.png", full_page=True)
    h.close()
    mp = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    mp.goto(BASE + "/")
    mp.wait_for_selector(".home-title")
    mp.screenshot(path=f"{OUT}/site-4-home-mobile.png", full_page=True)
    mp.close()

    # Dashboard (desktop)
    d = browser.new_page(viewport={"width": 1280, "height": 900})
    d.goto(BASE + "/dashboard/jordan-and-taylor")
    d.wait_for_selector("text=The Wedding Album")
    d.fill("input[type=password]", "wrong password")
    d.click("button[type=submit]")
    d.wait_for_selector("text=That password is not right")
    check(True, "wrong dashboard password rejected")
    d.screenshot(path=f"{OUT}/desktop-1-login.png")
    d.fill("input[type=password]", "correct horse battery")
    d.click("button[type=submit]")
    d.wait_for_selector("text=Media collected")
    d.wait_for_selector(".tile img")
    d.wait_for_timeout(500)
    d.screenshot(path=f"{OUT}/desktop-2-dashboard.png")
    check(d.locator(".tile").count() == 50, "first page loads 50 items")
    d.mouse.wheel(0, 20000)
    d.wait_for_timeout(1200)
    check(d.locator(".tile").count() == 64, "infinite scroll loads the rest")

    d.locator(".tile-btn").nth(2).click()
    d.wait_for_selector(".viewer")
    d.keyboard.press("ArrowRight")
    d.wait_for_timeout(200)
    d.screenshot(path=f"{OUT}/desktop-3-viewer.png")
    d.click("text=Hide")
    d.wait_for_timeout(500)
    d.keyboard.press("Escape")
    check(d.locator(".tile").count() == 63, "hidden item removed from gallery")
    d.click("role=tab[name='Hidden']")
    d.wait_for_timeout(800)
    d.wait_for_selector(".tile")
    check(d.locator(".tile").count() == 1, "hidden filter shows it")

    d.click("text=Download all")
    d.click("text=Prepare download")
    d.wait_for_selector("text=Photos — part 1 of 2")
    d.screenshot(path=f"{OUT}/desktop-4-download.png")
    d.click("text=Event settings")
    d.wait_for_timeout(600)
    d.screenshot(path=f"{OUT}/desktop-5-settings.png")
    check(d.locator("text=Download QR code").is_enabled(), "QR code generated")
    d.set_input_files(".cover-panel input[type=file]", [jpg("us.jpg")])
    d.wait_for_selector(".cover-preview img")
    check(d.locator("text=Change photo").count() == 1, "couple photo uploaded from settings")
    d.wait_for_timeout(400)
    d.screenshot(path=f"{OUT}/desktop-6-cover-settings.png")
    g = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    g.goto(BASE + "/e/jordan-and-taylor")
    g.wait_for_selector(".cover img")
    check(True, "guest page shows the couple photo")
    g.wait_for_timeout(400)
    g.screenshot(path=f"{OUT}/iphone-8-cover.png")
    g.close()

    d.click("text=Sign out")
    d.wait_for_selector("text=The Wedding Album")
    check(True, "logout returns to login")

    m = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    m.goto(BASE + "/dashboard/jordan-and-taylor")
    m.fill("input[type=password]", "correct horse battery")
    m.click("button[type=submit]")
    m.wait_for_selector(".tile img")
    m.wait_for_timeout(500)
    m.screenshot(path=f"{OUT}/iphone-7-dashboard.png")
    check(m.locator(".dash-footer a[href='/help#hosts']").count() == 1, "dashboard links to host help")
    check(m.locator(".dash-footer a[href^='mailto:']").count() == 1, "dashboard shows support email")
    m.close()

    # Guest page links to guest help
    g = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    g.goto(BASE + "/e/jordan-and-taylor")
    g.wait_for_selector(".guest-links")
    check(g.locator(".guest-links a[href='/help#guests']").count() == 1, "upload page links to guest help")
    g.close()

    # Help, legal pages, footer
    p2 = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    p2.goto(BASE + "/help#hosts")
    p2.wait_for_selector("text=How do I download everything?")
    p2.click("text=How do I download everything?")
    p2.wait_for_timeout(300)
    p2.screenshot(path=f"{OUT}/help-hosts.png")
    p2.goto(BASE + "/help#guests")
    p2.wait_for_selector("text=How do I upload?")
    p2.click("text=How do I upload?")
    p2.wait_for_timeout(300)
    p2.screenshot(path=f"{OUT}/help-guests.png")
    check(p2.locator(".site-footer a[href^='mailto:']").count() == 1, "footer shows support email")
    for path, title in [("/terms", "Terms of Service"), ("/privacy", "Privacy Policy"), ("/refunds", "Refund Policy")]:
        p2.goto(BASE + path)
        p2.wait_for_selector(f"h1:has-text('{title}')")
        check(p2.locator(f".site-footer a[href='{path}']").count() == 1, f"{title} page and footer link")
    p2.goto(BASE + "/terms")
    p2.screenshot(path=f"{OUT}/legal-terms.png", full_page=True)
    p2.close()

    # Forgot and reset password
    f = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    f.request.post(BASE + "/.netlify/functions/dashboard-logout")
    f.goto(BASE + "/dashboard/jordan-and-taylor")
    f.wait_for_selector("text=The Wedding Album")
    f.click("text=Forgot password?")
    f.fill("input[type=email]", "host@example.com")
    f.click("text=Email me a reset link")
    f.wait_for_selector("text=a reset link is on its way")
    f.screenshot(path=f"{OUT}/forgot-sent.png")
    check(stats()["mockLog"]["forgot"][-1] == {"slug": "jordan-and-taylor", "email": "host@example.com"}, "forgot password request sent")
    f.goto(BASE + "/dashboard/jordan-and-taylor?reset=expired-token-123456789")
    f.wait_for_selector("text=Choose a new password")
    f.fill("input[autocomplete=new-password] >> nth=0", "brand new pass")
    f.fill("input[autocomplete=new-password] >> nth=1", "brand new pass")
    f.click("text=Save and sign in")
    f.wait_for_selector("text=This reset link has expired")
    check(True, "bad reset link explained")
    f.goto(BASE + "/dashboard/jordan-and-taylor?reset=good-token-1234567890abcdef")
    f.wait_for_selector("text=Choose a new password")
    f.screenshot(path=f"{OUT}/reset-form.png")
    f.fill("input[autocomplete=new-password] >> nth=0", "brand new pass")
    f.fill("input[autocomplete=new-password] >> nth=1", "brand new pass")
    f.click("text=Save and sign in")
    f.wait_for_selector("text=Your new password is saved.")
    check("reset=" not in f.url, "reset token removed from address bar")

    # Edit page and extend hosting
    f.click("text=Event settings")
    f.wait_for_selector("text=Edit your page")
    f.fill(".edit-event input", "Share your favorite moments!")
    f.fill(".edit-event textarea", "Thank you for celebrating with us.")
    f.click(".edit-event button.starter:has-text('Garden')")
    f.click("text=Save changes")
    f.wait_for_selector("text=Guests will see the changes")
    check(True, "edit event saved")
    f.wait_for_timeout(500)
    f.screenshot(path=f"{OUT}/edit-event.png", full_page=True)
    check(f.locator("text=Storage used").count() == 1 and f.locator("text=6.2 GB of 25 GB").count() == 1, "storage used shown")
    f.click("text=Extend hosting $19")
    f.wait_for_selector("text=hosted until June 12, 2029")
    check(stats()["mockLog"]["extend"] == 1, "extend hosting opens checkout and confirms")
    f.screenshot(path=f"{OUT}/extended.png")
    f.close()

    # Admin
    a = browser.new_page(viewport={"width": 1280, "height": 900})
    a.goto(BASE + "/admin")
    a.wait_for_selector("text=Admin password")
    a.fill("input[type=password]", "nope")
    a.click("button[type=submit]")
    a.wait_for_selector("text=That password is not right")
    a.fill("input[type=password]", "owner admin pass")
    a.click("button[type=submit]")
    a.wait_for_selector("text=Paid events")
    check(a.locator(".admin-table tbody tr").count() == 3, "admin hides unpaid drafts by default")
    a.check(".admin-tools .agree input")
    check(a.locator(".admin-table tbody tr").count() == 4, "admin can show drafts")
    a.screenshot(path=f"{OUT}/admin.png", full_page=True)
    a.once("dialog", lambda dlg: dlg.accept())
    a.click(".admin-table tbody tr >> nth=0 >> text=Reset password")
    a.wait_for_selector(".reset-link input")
    check(stats()["mockLog"]["admin"][-1] == {"slug": "jordan-and-taylor", "action": "reset_password"}, "admin reset password action")
    a.once("dialog", lambda dlg: dlg.accept())
    a.click(".admin-table tbody tr >> nth=0 >> text=Extend 12 months")
    a.wait_for_selector("text=Hosting now ends")
    check(True, "admin extend action")
    am = browser.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True)
    am.goto(BASE + "/admin")
    am.wait_for_selector("text=Paid events")
    am.screenshot(path=f"{OUT}/admin-mobile.png", full_page=True)
    am.close()
    a.close()
    browser.close()

print(f"\n{len(failures)} failures")
sys.exit(1 if failures else 0)
